### ISSUE TITLE
Consider making pyopencl an optional dependency.

### ISSUE THREAD

**Issue by adamltyson** [tlambert03/napari-ndtiffs#1]
This plugin is really useful for simple lazy loading of tiff series, (without the deskewing for LLS files). I'd like to include it with [cellfinder](https://github.com/SainsburyWellcomeCentre/cellfinder) so users can easily view their raw data along with results.

However, `pyopencl` [seems to have issues on Windows](https://travis-ci.com/github/SainsburyWellcomeCentre/cellfinder/jobs/383295130), and I'd rather not introduce potential`pyopencl` build issues when it's not required for my purpose (and `napari-nftiffs` can fall back to scipy if needed).

It would be great if `napari-ndtiffs` could make `pyopencl` optional (e.g. `pip install napari-ndtiffs[opencl]`). If you want to keep `pyopencl` as a requirement, no worries, I can release a fork without the requirement.

Thanks!

**Comment by tlambert03** [comment]
Fine with me!  Would you be able to submit a PR adding the `opencl` extra?

**Comment by adamltyson** [comment]
No problem, I'll do it tomorrow.

**Comment by tlambert03** [comment]
thanks!  while we're chatting.  Feel free to make any other suggestions that you think would make this more general purpose.  One I've (passively) planned on eventually implementing was a way to accept some sort of filename pattern template that would let the user more easily parse arbitrary filename patterns (e.g. to extract the various axes of the dataset).  Generally curious to hear how you've been using it...

**Comment by adamltyson** [comment]
So for now, I've just been using it so I didn't have to make my own plugin for lazy loading.

I'm making a plugin to visualise [cellfinder](https://github.com/SainsburyWellcomeCentre/cellfinder) results (detected cell positions, brain region segmentation borders). Typically users will have their raw data (100-1000GB) and their processed data (100MB-10GB) in different places. It makes more sense for them to load the raw data using this plugin, then load the analysis results separately, so I don't have to do anything clever with file links etc.

For this specific purpose, we don't need anything clever with filename patterns. There are no timepoints, just very big structural images. Recursive loading of sub-directories (each with a separate channel) could be useful though.

**Comment by adamltyson** [comment]
Added in #2

**Comment by tlambert03** [comment]
thanks again @adamltyson.  I released v0.1.1 on PyPI with your updates.
