### ISSUE TITLE
Delay pyopencl warning until used

### ISSUE THREAD

**Issue by jni** [tlambert03/napari-ndtiffs#3]
When I try to open a folder that is not openable by napari-ndtiffs (it contains only zips, no tiffs), I nevertheless get the following warning:

WARNING:napari_ndtiffs.affine:Could not import pyopencl. Falling back to scipy for CPU affine transforms

At this particular juncture I did not really care about this and it was just annoying noise. 😄 Perhaps the warning can be postponed until an affine transform actually has to be performed?

**Comment by tlambert03** [comment]
finally got it done 😂

**Comment by tlambert03** [comment]
> (it contains only zips, no tiffs)

oh actually... by the way, this package _does_ read zips! :)

**Comment by jni** [comment]
Awesome! I looooove way-old issues getting closed. 😂
